---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - localstack.cloud.localstack.cloud
  resources:
  - localstacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - localstack.cloud.localstack.cloud
  resources:
  - localstacks/finalizers
  verbs:
  - update
- apiGroups:
  - localstack.cloud.localstack.cloud
  resources:
  - localstacks/status
  verbs:
  - get
  - patch
  - update
