apiVersion: apps/v1
kind: Deployment
metadata:
  name: devpod
  namespace: eks-lstack1-ns
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep", "604800"]
      nodeSelector:
        beta.kubernetes.io/os: linux