apiVersion: localstack.cloud.localstack.cloud/v1alpha1
kind: Localstack
metadata:
  name: env-0
  namespace: robert
spec:
  image: localstack/localstack:latest
  env:
  - name: SERVICES
    value: s3
  debug: true

  dns_provider: coredns
  dns_config_name: coredns
  dns_config_namespace: kube-system
