apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
           
        }
        cache 30
        loop
        reload
        loadbalance
    }
    localhost.localstack.cloud:53 {
            errors
            cache 5
            forward . 10.100.0.53
    }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system

