image:
  repository: "$LOCALSTACK_IMAGE_NAME"
  tag: "$LOCALSTACK_IMAGE_TAG"

service:
  clusterIP: "10.100.0.42"

extraEnvVars:
  - name: LOCALSTACK_AUTH_TOKEN
    value: "$LOCALSTACK_AUTH_TOKEN"
  - name: GATEWAY_LISTEN
    value: "0.0.0.0:4566"
  - name: DNS_RESOLVE_IP
    value: "10.100.0.42"

# enable debugging
debug: true

lambda:
  # The lambda runtime executor.
  # Depending on the value, LocalStack will execute lambdas either in docker containers or in kubernetes pods
  # The value "kubernetes" depends on the service account and pod role being activated
  executor: "kubernetes"
  environment_timeout: 400

  security_context:
    runAsUser: 1000
    fsGroup: 1000

resources:
  requests:
    cpu: 2000m
    memory: 4Gi

readinessProbe:
  initialDelaySeconds: 60

livenessProbe:
  initialDelaySeconds: 60
