image:
  repository: "$LOCALSTACK_IMAGE_NAME"
  tag: "$LOCALSTACK_IMAGE_TAG"

command:
  - /bin/bash
  - -c
  - echo 'ulimit -Sn 32767' >> /root/.bashrc && echo 'ulimit -Su 16383' >> /root/.bashrc && docker-entrypoint.sh

nameOverride: "localstack"
fullnameOverride: "localstack"
dnsPolicy: "${DNS_POLICY}"

service:
  clusterIP: "10.100.${NS_NUM}.42"
  dnsService: true
  edgeService:
    nodePort: ${NODE_PORT}

extraEnvVars:
  - name: LOCALSTACK_AUTH_TOKEN
    value: "$LOCALSTACK_AUTH_TOKEN"
  - name: GATEWAY_LISTEN
    value: "0.0.0.0:4566"
  - name: DNS_RESOLVE_IP
    value: "10.100.${NS_NUM}.42"
  - name: LOCALSTACK_HOST
    value: "localstack${NS_NUM}:4566"

# enable debugging
#debug: true

lambda:
  # The lambda runtime executor.
  # Depending on the value, LocalStack will execute lambdas either in docker containers or in kubernetes pods
  # The value "kubernetes" depends on the service account and pod role being activated
  executor: "kubernetes"
  environment_timeout: 400

  security_context:
    runAsUser: 1000
    fsGroup: 1000

readinessProbe:
  initialDelaySeconds: 60

livenessProbe:
  initialDelaySeconds: 60
