name: Weekly Test of Localstack deploy on EKS

on:
  schedule:
    - cron: '0 9 * * 1'  # Run every Monday at 9:00 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Install prerequisites
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Start Cluster
    - name: Setup EKS anywhere
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
      run: |
        # Unset stale org secret
        printenv
        unset LOCALSTACK_API_KEY

        # Set up EKS anywhere
