name: Weekly Test of Localstack deploy on EKS

on:
  schedule:
    - cron: '0 9 * * 1'  # Run every Monday at 9:00 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Dependencies
      run:
        sudo apt-get update
        sudo apt-get install -y \
          run-one \
          make

    - name: Setup EKS anywhere
      env:
        NS_NUM: "0"
      run: |
        # Unset stale org secret.
        printenv
        unset LOCALSTACK_API_KEY

        # Set up EKS anywhere.
        make local-setup-cluster NS_NUM=$NS_NUM
        make local-bootstrap NS_NUM=$NS_NUM
        make patch-coredns NS_NUM=$NS_NUM

    - name: Deploy Localstack
      env:
        LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        NS_NUM: "0"
      run: |
        make deploy-setup NS_NUM=$NS_NUM
        make deploy-localstack NS_NUM=$NS_NUM
    
    - name: Copy Test Script
      env:
        NS_NUM: "0"
      run: |
        DEV_POD_NAME=$(kubectl get pods -l app=devxpod -n ls$(NS_NUM) -o jsonpath="{.items[0].metadata.name}")
        kubectl cp .github/workflows/test.sh ls$(NS_NUM)/$DEV_POD_NAME:/tmp/test.sh -n ls$(NS_NUM)

    - name: Run Test Script
      env:
        NS_NUM: "0"
      run: |
        run-one-until-success make exec-devpod-noninteractive CMD="ls"
        make exec-devpod-noninteractive CMD="chmod +x /tmp/test.sh && /tmp/test.sh"
